[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    sui77/rc-switch
    bblanchon/ArduinoJson